# Generated by Django 2.2.10 on 2020-09-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Атомобили'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Атомобили'},
        ),
        migrations.AlterField(
            model_name='review',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Car', verbose_name='Машина'),
        ),
    ]
